// Code generated by MockGen. DO NOT EDIT.
// Source: wrapper.go

// This package is a generated GoMock package.
package node

import (
	gomock "github.com/golang/mock/gomock"
	v1alpha1 "github.com/tmax-cloud/hypersds-operator/api/v1alpha1"
	reflect "reflect"
)

// MockNodeInitInterface is a mock of NodeInitInterface interface
type MockNodeInitInterface struct {
	ctrl     *gomock.Controller
	recorder *MockNodeInitInterfaceMockRecorder
}

// MockNodeInitInterfaceMockRecorder is the mock recorder for MockNodeInitInterface
type MockNodeInitInterfaceMockRecorder struct {
	mock *MockNodeInitInterface
}

// NewMockNodeInitInterface creates a new mock instance
func NewMockNodeInitInterface(ctrl *gomock.Controller) *MockNodeInitInterface {
	mock := &MockNodeInitInterface{ctrl: ctrl}
	mock.recorder = &MockNodeInitInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockNodeInitInterface) EXPECT() *MockNodeInitInterfaceMockRecorder {
	return m.recorder
}

// NewNodesFromCephCr mocks base method
func (m *MockNodeInitInterface) NewNodesFromCephCr(cephSpec v1alpha1.CephClusterSpec) ([]NodeInterface, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewNodesFromCephCr", cephSpec)
	ret0, _ := ret[0].([]NodeInterface)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewNodesFromCephCr indicates an expected call of NewNodesFromCephCr
func (mr *MockNodeInitInterfaceMockRecorder) NewNodesFromCephCr(cephSpec interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewNodesFromCephCr", reflect.TypeOf((*MockNodeInitInterface)(nil).NewNodesFromCephCr), cephSpec)
}
