// Code generated by MockGen. DO NOT EDIT.
// Source: new_node_wrapper.go

// This package is a generated GoMock package.
package node

import (
	gomock "github.com/golang/mock/gomock"
	v1alpha1 "github.com/tmax-cloud/hypersds-operator/api/v1alpha1"
	reflect "reflect"
)

// MockNewNodeInterface is a mock of NewNodeInterface interface
type MockNewNodeInterface struct {
	ctrl     *gomock.Controller
	recorder *MockNewNodeInterfaceMockRecorder
}

// MockNewNodeInterfaceMockRecorder is the mock recorder for MockNewNodeInterface
type MockNewNodeInterfaceMockRecorder struct {
	mock *MockNewNodeInterface
}

// NewMockNewNodeInterface creates a new mock instance
func NewMockNewNodeInterface(ctrl *gomock.Controller) *MockNewNodeInterface {
	mock := &MockNewNodeInterface{ctrl: ctrl}
	mock.recorder = &MockNewNodeInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockNewNodeInterface) EXPECT() *MockNewNodeInterfaceMockRecorder {
	return m.recorder
}

// NewNodesFromCephCr mocks base method
func (m *MockNewNodeInterface) NewNodesFromCephCr(cephSpec v1alpha1.CephClusterSpec) ([]NodeInterface, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewNodesFromCephCr", cephSpec)
	ret0, _ := ret[0].([]NodeInterface)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewNodesFromCephCr indicates an expected call of NewNodesFromCephCr
func (mr *MockNewNodeInterfaceMockRecorder) NewNodesFromCephCr(cephSpec interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewNodesFromCephCr", reflect.TypeOf((*MockNewNodeInterface)(nil).NewNodesFromCephCr), cephSpec)
}
