#!/usr/bin/ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

$OS = "ubuntu/bionic64"
$username = "ceph"
$password = "cephceph"
$ips = ["192.168.99.111", "192.168.99.112", "192.168.99.113"]
$hdds = ["./hdd1.vdi", "./hdd2.vdi", "./hdd3.vdi"]

Vagrant.configure("2") do |config|
  config.vm.provision :shell, 
    privileged: true, 
    inline: <<-SHELL
      useradd #$username -p $(openssl passwd -1 #$password) -m --groups sudo -s /bin/bash
      sed -i 's/\#PermitRootLogin prohibit-password/PermitRootLogin yes/g' /etc/ssh/sshd_config
      sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
      systemctl restart sshd
      echo "#$password\n#$password\n" | passwd
      mkdir -p /working/config
    SHELL

  (1..$ips.length).each do |i|
    config.vm.define "node#{i}" do |node|
      node.vm.hostname = "node#{i}"
      node.vm.box = $OS
      node.vm.network "private_network", ip: $ips[i-1]
      node.disksize.size = "30GB"
      node.vm.provider :virtualbox do |vb|
        vb.cpus = 2
        vb.memory = "2048"
        unless File.exist?($hdds[i-1])
          vb.customize ['createhd', '--filename', $hdds[i-1], '--size', 20 * 1024]
        end
        vb.customize ['storageattach', :id, 
          '--storagectl', 'SCSI' , '--port', 2, '--device', 0,
          '--type', 'hdd', '--medium', $hdds[i-1]]
      end
    end
  end
end
