name: Pull Request Linter Check
on: [pull_request]
jobs:
  linter:
    if: "! contains(github.event.pull_request.body, '[skip-ci]')"
    strategy:
      matrix:
        os: [ubuntu-18.04]
    name: Run Linter Check
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    steps:
    - name: Check out the code
      uses: actions/checkout@v2
    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v2
      with: 
        version: v1.29
        args: -E gosec,goconst,gofmt,goimports,unparam,govet
